/**
 * S&P 500 주요 종목 — 시가총액 상위 150개
 * VSA 스캐너용 유니버스
 */
export interface SP500Stock {
  symbol: string;
  name: string;
  sector: string;
}

export const SP500_UNIVERSE: SP500Stock[] = [
  // 기술
  { symbol: 'AAPL',  name: 'Apple',              sector: '기술' },
  { symbol: 'MSFT',  name: 'Microsoft',          sector: '기술' },
  { symbol: 'NVDA',  name: 'NVIDIA',             sector: '기술' },
  { symbol: 'GOOGL', name: 'Alphabet A',         sector: '기술' },
  { symbol: 'META',  name: 'Meta Platforms',     sector: '기술' },
  { symbol: 'AVGO',  name: 'Broadcom',           sector: '기술' },
  { symbol: 'TSLA',  name: 'Tesla',              sector: '기술' },
  { symbol: 'ORCL',  name: 'Oracle',             sector: '기술' },
  { symbol: 'CRM',   name: 'Salesforce',         sector: '기술' },
  { symbol: 'AMD',   name: 'AMD',                sector: '기술' },
  { symbol: 'ADBE',  name: 'Adobe',              sector: '기술' },
  { symbol: 'QCOM',  name: 'Qualcomm',           sector: '기술' },
  { symbol: 'TXN',   name: 'Texas Instruments',  sector: '기술' },
  { symbol: 'AMAT',  name: 'Applied Materials',  sector: '기술' },
  { symbol: 'MU',    name: 'Micron Technology',  sector: '기술' },
  { symbol: 'INTC',  name: 'Intel',              sector: '기술' },
  { symbol: 'KLAC',  name: 'KLA Corp',           sector: '기술' },
  { symbol: 'LRCX',  name: 'Lam Research',       sector: '기술' },
  { symbol: 'MRVL',  name: 'Marvell Technology', sector: '기술' },
  { symbol: 'NXPI',  name: 'NXP Semiconductors', sector: '기술' },
  // 금융
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', sector: '금융' },
  { symbol: 'JPM',   name: 'JPMorgan Chase',     sector: '금융' },
  { symbol: 'V',     name: 'Visa',               sector: '금융' },
  { symbol: 'MA',    name: 'Mastercard',         sector: '금융' },
  { symbol: 'BAC',   name: 'Bank of America',    sector: '금융' },
  { symbol: 'WFC',   name: 'Wells Fargo',        sector: '금융' },
  { symbol: 'GS',    name: 'Goldman Sachs',      sector: '금융' },
  { symbol: 'MS',    name: 'Morgan Stanley',     sector: '금융' },
  { symbol: 'BLK',   name: 'BlackRock',          sector: '금융' },
  { symbol: 'SCHW',  name: 'Charles Schwab',     sector: '금융' },
  { symbol: 'AXP',   name: 'American Express',   sector: '금융' },
  { symbol: 'CB',    name: 'Chubb',              sector: '금융' },
  { symbol: 'MMC',   name: 'Marsh McLennan',     sector: '금융' },
  { symbol: 'PGR',   name: 'Progressive',        sector: '금융' },
  { symbol: 'C',     name: 'Citigroup',          sector: '금융' },
  // 헬스케어
  { symbol: 'UNH',   name: 'UnitedHealth',       sector: '헬스케어' },
  { symbol: 'LLY',   name: 'Eli Lilly',          sector: '헬스케어' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',  sector: '헬스케어' },
  { symbol: 'ABBV',  name: 'AbbVie',             sector: '헬스케어' },
  { symbol: 'MRK',   name: 'Merck',              sector: '헬스케어' },
  { symbol: 'TMO',   name: 'Thermo Fisher',      sector: '헬스케어' },
  { symbol: 'ABT',   name: 'Abbott Labs',        sector: '헬스케어' },
  { symbol: 'DHR',   name: 'Danaher',            sector: '헬스케어' },
  { symbol: 'PFE',   name: 'Pfizer',             sector: '헬스케어' },
  { symbol: 'BMY',   name: 'Bristol-Myers',      sector: '헬스케어' },
  { symbol: 'AMGN',  name: 'Amgen',              sector: '헬스케어' },
  { symbol: 'GILD',  name: 'Gilead Sciences',    sector: '헬스케어' },
  { symbol: 'ISRG',  name: 'Intuitive Surgical', sector: '헬스케어' },
  { symbol: 'VRTX',  name: 'Vertex Pharma',      sector: '헬스케어' },
  { symbol: 'REGN',  name: 'Regeneron',          sector: '헬스케어' },
  // 소비재
  { symbol: 'AMZN',  name: 'Amazon',             sector: '소비재' },
  { symbol: 'COST',  name: 'Costco',             sector: '소비재' },
  { symbol: 'WMT',   name: 'Walmart',            sector: '소비재' },
  { symbol: 'HD',    name: 'Home Depot',         sector: '소비재' },
  { symbol: 'MCD',   name: "McDonald's",         sector: '소비재' },
  { symbol: 'NKE',   name: 'Nike',               sector: '소비재' },
  { symbol: 'SBUX',  name: 'Starbucks',          sector: '소비재' },
  { symbol: 'TGT',   name: 'Target',             sector: '소비재' },
  { symbol: 'LOW',   name: "Lowe's",             sector: '소비재' },
  { symbol: 'TJX',   name: 'TJX Companies',      sector: '소비재' },
  { symbol: 'BKNG',  name: 'Booking Holdings',  sector: '소비재' },
  { symbol: 'MAR',   name: 'Marriott',           sector: '소비재' },
  { symbol: 'ABNB',  name: 'Airbnb',             sector: '소비재' },
  // 필수소비재
  { symbol: 'PG',    name: 'Procter & Gamble',   sector: '필수소비재' },
  { symbol: 'KO',    name: 'Coca-Cola',          sector: '필수소비재' },
  { symbol: 'PEP',   name: 'PepsiCo',            sector: '필수소비재' },
  { symbol: 'PM',    name: 'Philip Morris',      sector: '필수소비재' },
  { symbol: 'MO',    name: 'Altria',             sector: '필수소비재' },
  { symbol: 'MDLZ',  name: 'Mondelez',           sector: '필수소비재' },
  { symbol: 'CL',    name: 'Colgate-Palmolive',  sector: '필수소비재' },
  { symbol: 'KMB',   name: 'Kimberly-Clark',     sector: '필수소비재' },
  // 에너지
  { symbol: 'XOM',   name: 'ExxonMobil',         sector: '에너지' },
  { symbol: 'CVX',   name: 'Chevron',            sector: '에너지' },
  { symbol: 'COP',   name: 'ConocoPhillips',     sector: '에너지' },
  { symbol: 'SLB',   name: 'Schlumberger',       sector: '에너지' },
  { symbol: 'EOG',   name: 'EOG Resources',      sector: '에너지' },
  { symbol: 'PSX',   name: 'Phillips 66',        sector: '에너지' },
  { symbol: 'VLO',   name: 'Valero Energy',      sector: '에너지' },
  { symbol: 'OXY',   name: 'Occidental',         sector: '에너지' },
  // 산업재
  { symbol: 'CAT',   name: 'Caterpillar',        sector: '산업재' },
  { symbol: 'RTX',   name: 'RTX Corp',           sector: '산업재' },
  { symbol: 'HON',   name: 'Honeywell',          sector: '산업재' },
  { symbol: 'GE',    name: 'GE Aerospace',       sector: '산업재' },
  { symbol: 'UPS',   name: 'UPS',                sector: '산업재' },
  { symbol: 'LMT',   name: 'Lockheed Martin',    sector: '산업재' },
  { symbol: 'BA',    name: 'Boeing',             sector: '산업재' },
  { symbol: 'DE',    name: 'Deere & Company',    sector: '산업재' },
  { symbol: 'GD',    name: 'General Dynamics',   sector: '산업재' },
  { symbol: 'NOC',   name: 'Northrop Grumman',   sector: '산업재' },
  { symbol: 'FDX',   name: 'FedEx',              sector: '산업재' },
  { symbol: 'EMR',   name: 'Emerson Electric',   sector: '산업재' },
  { symbol: 'ETN',   name: 'Eaton',              sector: '산업재' },
  { symbol: 'PH',    name: 'Parker-Hannifin',    sector: '산업재' },
  // 커뮤니케이션
  { symbol: 'NFLX',  name: 'Netflix',            sector: '커뮤니케이션' },
  { symbol: 'DIS',   name: 'Disney',             sector: '커뮤니케이션' },
  { symbol: 'CMCSA', name: 'Comcast',            sector: '커뮤니케이션' },
  { symbol: 'T',     name: 'AT&T',               sector: '커뮤니케이션' },
  { symbol: 'VZ',    name: 'Verizon',            sector: '커뮤니케이션' },
  { symbol: 'TMUS',  name: 'T-Mobile',           sector: '커뮤니케이션' },
  { symbol: 'WBD',   name: 'Warner Bros Discovery', sector: '커뮤니케이션' },
  // 유틸리티/부동산
  { symbol: 'NEE',   name: 'NextEra Energy',     sector: '유틸리티' },
  { symbol: 'DUK',   name: 'Duke Energy',        sector: '유틸리티' },
  { symbol: 'SO',    name: 'Southern Company',   sector: '유틸리티' },
  { symbol: 'AMT',   name: 'American Tower',     sector: '부동산' },
  { symbol: 'PLD',   name: 'Prologis',           sector: '부동산' },
  { symbol: 'SPG',   name: 'Simon Property',     sector: '부동산' },
  // 소재
  { symbol: 'LIN',   name: 'Linde',              sector: '소재' },
  { symbol: 'SHW',   name: 'Sherwin-Williams',   sector: '소재' },
  { symbol: 'FCX',   name: 'Freeport-McMoRan',   sector: '소재' },
  { symbol: 'NEM',   name: 'Newmont',            sector: '소재' },
  { symbol: 'NUE',   name: 'Nucor',              sector: '소재' },
];

export const SP500_SECTORS = [...new Set(SP500_UNIVERSE.map(s => s.sector))];
